import { sora } from "@/lib/fonts/fonts";
import "./globals.css";

export const metadata = {
  title: "Help Me Out - Screen Recorder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sora.className}>{children}</body>
    </html>
  );
}
